blocker.py
Grow-with-Open-Source/Python-Projects pull request #14
Opened 2023-10-28 17:17 UTC by ShashiNova

2023-10-28 18:11 UTC, iamwatchdogs reviewed
@ShashiNova it's recommended to add a `README.md` file.

2023-10-28 18:15 UTC, iamwatchdogs requested changes
@ShashiNova Please make the required changes.

2023-10-28 18:15 UTC, iamwatchdogs commented on blocker.py
> +if _name_ == "_main_":
I went through your code as the linting checks have not passed and found this issue. Please fix this syntactical error and test your code once again.

```suggestion
if __name__ == "_main_":
```

2023-10-29 16:28 UTC, iamwatchdogs requested changes
Please make the requested changes both for lining checks _(previous code review)_ and maintain the file structure.

2023-10-29 16:28 UTC, iamwatchdogs commented on blocker.py
@ShashiNova Please place your project files within a directory/folder named with your project name.

2023-10-29 16:44 UTC, ShashiNova commented on blocker.py
I have moved the project files into the required folder.

2023-10-29 16:45 UTC, iamwatchdogs approved these changes
The requested changes have been made. Review and Approved by @iamwatchdogs.

2023-10-29 16:45 UTC, merged

2023-10-29 16:46 UTC, iamwatchdogs commented
Thank you for contributing @ShashiNova, make sure to check your contributions on [GitHub Pages](https://grow-with-open-source.github.io/Python-Projects/).