File organizer
Grow-with-Open-Source/Python-Projects pull request #15
Opened 2023-10-29 00:15 UTC by adedayoprcs

I created a File Organizer.

2023-10-29 05:06 UTC, iamwatchdogs requested changes
Please @adedayoprcs make the requested changes.

2023-10-29 05:06 UTC, iamwatchdogs commented on File_Organizer/file-organizer.py
Please remove the additional empty new lines.

2023-10-30 08:43 UTC, adedayoprcs commented on File_Organizer/file-organizer.py
Thank you for the correction, I've made the changes

2023-10-30 09:08 UTC, iamwatchdogs approved these changes
Requested changes have been made. Reviewed and Approved by @iamwatchdogs.

2023-10-30 09:08 UTC, merged

2023-10-30 09:09 UTC, iamwatchdogs commented
Thank you for contributing @adedayoprcs, make sure to check your contributions on [GitHub Pages](https://grow-with-open-source.github.io/Python-Projects/).