Number guessing game
Grow-with-Open-Source/Python-Projects pull request #17
Opened 2023-10-30 15:05 UTC by adedayoprcs

I created a simple number guessing game.

2023-10-30 18:37 UTC, iamwatchdogs requested changes
Please make the requested changes.

2023-10-30 18:37 UTC, iamwatchdogs commented on Number-Guessing/number-guessing
Please rename the file with the extension as `.py`

2023-10-30 19:41 UTC, adedayoprcs commented on Number-Guessing/number-guessing
File has been renamed.

2023-10-31 01:17 UTC, iamwatchdogs requested changes
Please make the requested changes.

2023-10-31 01:17 UTC, iamwatchdogs commented on Number-Guessing/number-guessing
@adedayoprcs Please check `Number-Guessing/number-guessing` file within your PR. Your filename still doesn't contain the `.py` file extension.

2023-10-31 08:22 UTC, closed without merging